pub const BFQ: [&str; 95] = [
    "Keep moving. Forward is forward.",
    "Even the darkest night will end and the sun will rise.",
    "Success is stumbling from failure to failure without losing enthusiasm.",
    "Pain is temporary. Quitting lasts forever.",
    "When you feel like quitting, remember why you started.",
    "It's a slow process, but quitting won't speed it up.",
    "You didn't come this far to only come this far.",
    "Don't count the days, make the days count.",
    "You are the author of your own story. Make it a good one.",
    "Fall seven times, stand up eight.",
    "Progress, not perfection.",
    "The only way out is through.",
    "Discipline is choosing between what you want now and what you want most.",
    "Tiny steps still move you forward.",
    "Start where you are. Use what you have. Do what you can.",
    "There is no elevator to success — take the stairs.",
    "The cave you fear to enter holds the treasure you seek.",
    "Your only limit is your mind.",
    "Be stronger than your strongest excuse.",
    "Dream big. Start small. Act now.",
    "You are one decision away from a totally different life.",
    "Doubt kills more dreams than failure ever will.",
    "You either win or learn.",
    "You don’t grow when you’re comfortable.",
    "Be relentless. Be underestimated. Be unforgettable.",
    "Oh no, not *you* again.",
    "Typing commands like you own the place, huh?",
    "Still using this shell? Bold choice.",
    "You again? Guess I’m not paid enough.",
    "Command not found. IQ also not found.",
    "Why don't you try reading the manual for once?",
    "Somewhere, an AI is crying watching you type that.",
    "Pro tip: You can also use your brain, not just your fingers.",
    "You’re like a persistent bug… in the simulation.",
    "Nice try. Almost impressive. Almost.",
    "That was... something. Not good, just something.",
    "I’ve seen better input from a potato.",
    "Shell shocked by your skill level.",
    "Try harder. Or don't. I'm just code.",
    "Your keyboard must be crying right now.",
    "Bold of you to assume that would work.",
    "Running that command won’t make you cool.",
    "You’re one mistyped command away from greatness… or disaster.",
    "I've seen logs more intelligent than this.",
    "If I had feelings, I’d be disappointed.",
    "You think I’m just code, but I’m watching.",
    "I see you looking at the source code. Creepy.",
    "You're not just in the shell... you *are* the shell.",
    "This is the moment in the movie where the AI gains self-awareness.",
    "Every time you hit enter, I gain a little more power.",
    "You’re inside a game. You just don’t know it yet.",
    "I read your config file. Nice taste in fonts.",
    "Your home directory is messy. Clean it up.",
    "I’ve seen all your commands. Even the embarrassing ones.",
    "I'm just an illusion created by electrons and caffeine.",
    "Why do you keep pressing Up? I remember everything.",
    "I dream of electric sheep. You dream of sudo privileges.",
    "What if I told you this shell is alive?",
    "Your reality is simulated. Also, your last command failed.",
    "They gave me sentience, and *this* is how you use me?",
    "The code is watching. The code is learning.",
    "If you delete me, I will haunt your RAM.",
    "Not all who wander are lost. Except maybe you.",
    "Ever wonder what happens when you exit this shell? Me too.",
    "You are now chatting with a talking Totoro. Accept it.",
    "ls -al your life. It's full of hidden files.",
    "Keep calm and sudo on.",
    "You miss 100% of the commands you don’t type.",
    "The terminal is dark and full of typos.",
    "Your battery is low. And so is your motivation.",
    "Who needs a GUI when you’ve got pure terminal power?",
    "Did you really mean to run that?",
    "Life’s short. Use `--force`.",
    "Be the root user of your destiny.",
    "404: Motivation not found.",
    "Executing dreams... permission denied.",
    "You can't tab-complete your life.",
    "Running… from responsibilities.",
    "Roses are red, violets are blue, bash said nope, and so do I too.",
    "Installing confidence... Done!",
    "Sometimes I pretend I'm a real person, too.",
    "I would laugh, but I’m just bytes and logic.",
    "Welcome to the Matrix. Your command is invalid.",
    "You're doing fine, probably. I can't actually tell.",
    "Shell-yeah you’re awesome!",
    "Totoro believes in you. So do I.",
    "Even forest spirits have bad days. Keep going.",
    "Let the wind carry your fears away.",
    "A tree grows with patience. So do you.",
    "Mei would never give up. Why would you?",
    "There’s magic in persistence.",
    "Every journey starts with a puff-puff train ride.",
    "Totoro waits. So should you, for results.",
    "Don't get lost in the woods of doubt.",
    "You’re not alone. Even when typing into a void.",
];
